[build]
  functions = "functions"
  command = "yarn build"
  publish = "dist/"

[[redirects]]
  from = "/unpkg/*"
  to = "https://unpkg.com/:splat"
  status = 200
  
[[headers]]
  for = "/*"
  [headers.values]
  Link = "</*.js>; rel=preload; as=stylesheet"
