[build]
  functions = "functions"
  command = "yarn init-prepare; yarn build  --log-level 0"
  publish = "dist/"

[[redirects]]
  from = "/unpkg/*"
  to = "https://unpkg.com/:splat"
  status = 200
  
